### ISSUE TITLE
Where's pt-display now?

### ISSUE THREAD

**Issue by codepope** [rricharz/pi-top-setup#5]
I noted that #2 was resolved by a new device-manager package no longer installing pt-display as that moved to another module. But that also means its not installed so if you do want it, where do you find it?

**Comment by rricharz** [comment]
I don‘t know. I propose that you ask pi-top. Open an issue on https://github.com/pi-top/Device-Management and tell them that you are installing pt-device-manager in Standard Raspbian.

**Comment by codepope** [comment]
Done. Thanks.

https://github.com/pi-top/Device-Management/issues/30
