### ISSUE TITLE
No Battery icon

### ISSUE THREAD

**Issue by prateekgeek** [rricharz/pi-top-setup#6]
I have Raspbian Stretch with pt-device-manager installed and I2C enabled. When I run pt-battery I get nothing, no error no output. I don't see any Battery (pi-top) widget in the Panel settings. Any ideas?

**Comment by rricharz** [comment]
If you install pi-top Configuration as described in this repository, check the output of the following commands:

pt-devices
pt-log

This should help you to identify the problem.
