### ISSUE TITLE
poweroff not installed

### ISSUE THREAD

**Issue by nielsbaloe** [rricharz/pi-top-setup#7]
Hi,

I see that in an older version, you had something called 'poweroff'. As in: when in Raspbian I use the software shutdown menu and choose "Shutdown", the PI 3B+ nicely shuts down as always, however the pi-top hub is still on. Right not I have to hold the power button for several button to set the power off, however sometimes I forget that and then the laptop battery is empty when I want to use the pi-top.

Any chance your utility is still out there, if so, how to install and use/enable it?

Super super thanks!!!!!!!!!!!!!!!!!
Niels

**Comment by rricharz** [comment]
I assume you are using a pi-top laptop rev 2 (with the sliding keyboard). My earlier shutdown program does not work on that system, but the pi-top software that you are installing as recommended in this repository does handle the shutdown in a way identical to my original shutdown program.

**Comment by nielsbaloe** [comment]
So many thanks for your time!!
Yes indeed it is the pi-top 2, with still a bit new-ish smell due to the packaging chemical stuff they use.

Hmm then I do not know whether we talk about the same thing. When I do a system shutdown, or when I press the off-button a second, then the system shuts off. However, at the back of the laptop, I can clearly see that the green light is still fully on. That is the on/off status of the hub right? That is not supposed to happen then right? I assume the whole thing should shut down too. Now I forget to push the on/off-button again for about 4 seconds to really shut it down.

Something I can do about it? pt-devices gives:
    Devices and peripherals handled by pt-devices-manager:
    OS release: 4.19.42-v7+
    Host device is pi-top V2

Super thanks for any hints

**Comment by rricharz** [comment]
The only idea I have to find out what does not work is to use the command

journalctl -u pt-device-manager --since=yesterday
then inspect the log carefully for anything unusual

**Comment by nielsbaloe** [comment]
Hi Rene,

Super thanks for your answer, that helped. there was a pi-v1 service incorrectly installed, removed it and voila.

Again thanks!
Niels

________________________________
Van: Rene Richarz <notifications@github.com>
Verzonden: vrijdag 14 juni 2019 16:25
Aan: rricharz/pi-top-setup
CC: nielsbaloe; Author
Onderwerp: Re: [rricharz/pi-top-setup] poweroff not installed (#7)


The only idea I have to find out what does not work is to use the command

journalctl -u pt-device-manager --since=yesterday
then inspect the log carefully for anything unusual
