### ISSUE TITLE
PI Top Ceed and RPI 4B

### ISSUE THREAD

**Issue by poetsmeniet** [rricharz/pi-top-setup#8]
pt-apps install fine through apt on RPI 4B (running raspbian bionic) and also this repo compiles fine.

No errors running the pt-brightness app, although the brightness does not change.. it this fixable?

**Comment by rricharz** [comment]
I have no CEED to test this. On my pi-top [3] laptop with RPi 3B pt-brightness still works properly using the latest Raspbian. Unfortunately it is not possible to mount a RPI 4B in the laptop.

I propose that you open an issue in [](https://github.com/pi-top/Device-Management).

**Comment by poetsmeniet** [comment]
Thanks, will do!
